### ISSUE TITLE
[Bug] Website Footer white in dark mode

### ISSUE THREAD

**Issue by SamharAeron** [typefaceoff/typefaceoff#137]
### Current Behavior

Currently when the website is switched to dark mode the footer becomes a very bright white colour.

### Expected Behavior

It seems appropriate that the footer would be a similar dark black or dark grey to suit the rest of the dark mode version.

### Changes Needed

Likely change the dark mode handling and css.

### Location of Issue

App.tsx, App.css

### Additional Context

Current look:
<img width="917" alt="image" src="https://github.com/typefaceoff/typefaceoff/assets/100731104/fc7f2ce8-0863-4ade-bdae-d9d60edb094d">

**Comment by jaskfla** [comment]
If I recall correctly, I set `color-scheme: light;` in the `index.css` to declare to the browser that dark mode was not implemented. It may now be wise to change that over to `color-scheme: light dark;` (I can’t remember what the default value is, so not sure if it’s redundant.)

Perhaps also worth considering `prefers-color-scheme` to save yourselves from adding/removing JavaScript fluff to add/remove classes? If the CSS variables used strategically (and a quick glance indicates that they generally are), you might even be able to just get away with defining the colour variables differently:

```css
@media (prefers-color-scheme: dark) {
    :root { /* Redefine the same CSS variables here */}
}
```

Ultimately it probably down to a stylistic preference; I’m quite a W3C purist so am biased towards certain methodologies. Take of that what you will!
