### ISSUE TITLE
[Bug] Just a typo that needs fixing

### ISSUE THREAD

**Issue by 100amps** [typefaceoff/typefaceoff#140]
### Current Behavior

Subtext says:  OpenType font feautres available:

"features" has a spelling mistake.

### Expected Behavior

Subtext should say:  OpenType font features available:

### Changes Needed

change feautres to features

### Location of Issue

Home screen

**Comment by jaskfla** [comment]
Great catch! Thanks for reporting this; I’ll try and make time to fix this over the weekend.
