### ISSUE TITLE
[Feature] Creating Placeholders for Text

### ISSUE THREAD

**Issue by jmadelino** [typefaceoff/typefaceoff#21]
### Feature Description

I want to add placeholders for a variety of different text sizes and types.

### Reason for Change

This change is required to show the user how each font looks in the different text sizes and types so that they may have a more informed opinion regarding deciding a font over another in their own project.

### Where are the changes needed?

I will have to create new files for the components required to achieve this.

**Comment by jaskfla** [comment]
I haven’t been in Figma for a few days. Have we got a template design yet? Regardless, seems sensible; I’m happy for you to gets started.

I suppose we can just default to `system-ui, sans-serif` or some sensible font stack like that—until Jace has drag-and-drop-a-font feature in place.
