### ISSUE TITLE
[Feature] Configurable Leading

### ISSUE THREAD

**Issue by cste303** [typefaceoff/typefaceoff#25]
### Feature Description

Allow users to adjust the line spacing (Leading) of the displayed fonts.

### Reason for Change

This allows the user to adjust the line spacing of the fonts they are looking at to be able to see the text closer to how it would be used in production.

### Where are the changes needed?

The changes will be made to the components that hold the fonts, as well as new files to be able to adjust it.

**Comment by jaskfla** [comment]
Approved.
