### ISSUE TITLE
[Feature] Update typeface off page title and logo

### ISSUE THREAD

**Issue by JC4github** [typefaceoff/typefaceoff#37]
### Feature Description

![image](https://github.com/typefaceoff/typefaceoff/assets/95055206/bb4598fb-d80d-4e63-8644-d733fc481b59)

Replace the default template page title and logo with our own

### Reason for Change

To move away from the default template and customise it into our own.

### Where are the changes needed?

It should be in the index header

**Comment by jaskfla** [comment]
Please do!

**Comment by jmadelino** [comment]
Completed by PR #40
