### ISSUE TITLE
[Feature] Flesh out proofing template

### ISSUE THREAD

**Issue by jaskfla** [typefaceoff/typefaceoff#39]
### Feature Description

I’d like to attempt implementing a proofing template somewhere in the realm of this mockup:

![Figma mockup](https://media.discordapp.net/attachments/1132870209196277812/1142786123605753856/Screenshot_2023-08-20T234336.png?width=1920&height=1068)

### Reason for Change

Typefaceoff is for viewing text, but right now the page doesn’t have *that* much text for proofing fonts.

### Where are the changes needed?

The one and only page we have!

**Comment by hwan513** [comment]
I approve.

Reach out if you need any help with implementation.
