### ISSUE TITLE
[Feature] Improved dropboxes for font files

### ISSUE THREAD

**Issue by tpo920** [typefaceoff/typefaceoff#46]
### Feature Description

For a more refined look, the `<input>` elements within the `<drop-area>` should be removed. Instead users should be able to click the `<drop-area>`  to choose font files. Font files that are uploaded in the  `<drop-area>` should be displayed their font name and styled with the corresponding font family.

### Reason for Change

The current  `<input>` elements  leads to bugs between the drag and drop functions. Removing these entirely would resolves these bugs and make the drop boxes look more refined.

### Where are the changes needed?

In the `FontUploader.tsx` and `App.tsx` and corresponding css files.

**Comment by jaskfla** [comment]
By “input boxes”, do you mean the `<input>` element we currently have within the `drop-area` with the dashed outline?

If I’m not misunderstanding, this sounds good.
