### ISSUE TITLE
[Feature] Setup Github Pages

### ISSUE THREAD

**Issue by hwan513** [typefaceoff/typefaceoff#50]
### Feature Description

Set up GitHub pages so that it can host a statically generated website from Vite with a GitHub action.

### Reason for Change

This makes the app accessible outside of localhost.

### Where are the changes needed?

This would probably require the addition of a new file in workflows.

**Comment by jaskfla** [comment]
Yes, please.

**Comment by hwan513** [comment]
Deployment is bugged

**Comment by hwan513** [comment]
Still not fixed

**Comment by hwan513** [comment]
Unfortunately, me on time pressure wasn't able to find the issue.
I believe I have found the fix and will leave this for the next group to work on.
Code was modified from https://vitejs.dev/guide/static-deploy.html

To fix deployment, the steps would be to: 

1. Uncomment all the lines in `.github/workflows/deploy.yml`
2. Add the line `base: '/typefaceoff/'`, underneath the `plugins: [react()],` line in `vite.config.ts`

Push and hopefully the deployment should work whenever someone pushes to main branch.
