### ISSUE TITLE
[Documentation] Update screenshot in README.

### ISSUE THREAD

**Issue by jaskfla** [typefaceoff/typefaceoff#58]
### Current Behavior

The screenshot of Typefaceoff in the README is outdated.

### Expected Behavior

Screenshot of Typefaceoff as it is today.

### Changes Needed

The screenshot.

### Location of Issue

In the README.

**Comment by jaskfla** [comment]
As discussed in Discord, I’ll also move the community documentation back into `/.github`

**Comment by jmadelino** [comment]
Looks like a good idea to me since our application has updated, hence our README should reflect that to give an accurate picture to the user and other contributors.
