### ISSUE TITLE
[Feature] Configurable Leading

### ISSUE THREAD

**Issue by jess-lowe** [typefaceoff/typefaceoff#64]
### Feature Description

Simply changing the typeface used to typeset a document does not lend itself to fair comparison between two choices. This is, in part, because the *point size* of a font is [surprisingly non-standard](https://tonsky.me/blog/font-size). Different typefaces need to be set at different point sizes, with different line spacing, to optically *appear* as though they’re otherwise typeset similarly.

The user should be able to adjust the line spacing (within a small but reasonable range) separately for each font being compared. This lets them see the text typeset closer to how they would use it in production, rather than having to optimise for one font at the detriment of the other.

> [!NOTE]
> **Leading** (pronounced *ledding*) is the traditional term for **line spacing**, because printers used to put strips of lead between lines to adjust line spacing.

### Reason for Change

Will allow a more fair comparison between fonts

### Where are the changes needed?

Likely within the App.tsx context

**Comment by SamharAeron** [comment]
This issue has already been resolved and merged in pull request #28, marking as duplicate and closing issue.
