### ISSUE TITLE
[Feature] Access/reveal OpenType features of a font

### ISSUE THREAD

**Issue by jess-lowe** [typefaceoff/typefaceoff#73]
### Feature Description

Add the capabilities to access the opentype features of a font to be used in later implementations for enabling/disabling opentype features. 
Child of Issue #65 

### Reason for Change

Will allow more customisation of the fonts

### Where are the changes needed?

App.tsx and across the FontPreview.tsx files is likely

### Anything Else?

https://github.com/opentypejs/opentype.js could be of use.

**Comment by mattysteves** [comment]
Functionality added by #86
